wso2/call-home

- src/main/java/org/wso2/callhome/CallHome.java
- src/main/java/org/wso2/callhome/utils/ExtractedInfo.java
> Remove the feature of extracting the user email.
> JDK versions - Oracle 1.8.0.191 
> Operating systems - Ubuntu 18.04
> Remove extracting user email function

- pom.xml
> Add SCM tag to pom.xml file
> List all JDK versions - Oracle JDK 1.8.0.191
> Operating systems - Ubuntu 18.04
> Add scm tag to pom.xml

- src/main/java/org/wso2/callhome/CallHome.java
> Trim the returned value after reading from the product.txt
> JDK - Oracle JDK 1.8.0
> Operating systems - Ubuntu  18.04
> Trim product name and version

- src/main/java/org/wso2/callhome/CallHome.java
> Encode query params
> JDK - Oracle JDK 1.8.0
> Operating systems - Ubuntu  18.04
> Encode query params

- src/main/java/org/wso2/callhome/internal/CallHome.java
> Fix issues in the comments and refractor the code
> List all JDK versions  - 1.8.191
> Operating systems - Ubuntu18.04
> Fix comments and refractor code

- src/main/java/org/wso2/callhome/utils/MessageFormatter.java
> Update CallHome message display format
> Change callhome message format

- pom.xml
- src/main/java/org/wso2/callhome/internal/CallHome.java
> Update carbon core and osgi framework versions for the 4.5.x kernel products.
> Run CallHome response in a separate thread
> Add CallHome osgi component to the carbon kernel 4.5.x product versions.
> Update osgi framework version and carbon core version

- pom.xml
- src/main/java/org/wso2/callhome/internal/CallHome.java
- src/main/java/org/wso2/callhome/internal/CallHomeActivator.java
- src/main/java/org/wso2/callhome/internal/CallHomeComponent.java
- src/main/java/org/wso2/callhome/internal/CallHomeObserver.java
- src/main/java/org/wso2/callhome/internal/DataHolder.java
> Add Apache HTTP client for the HTTPS connections
> Use product truststore for the socket factory
> Fix SSL issue occurred while using default SSL context.
> JDK - 1.8.0
> OS - Ubuntu 18.04
> Use Apache HTTP client

- pom.xml
- src/main/java/org/wso2/callhome/CallHomeExecutor.java
- src/main/java/org/wso2/callhome/core/CallHome.java
- src/main/java/org/wso2/callhome/core/DataHolder.java
- src/main/java/org/wso2/callhome/exception/CallHomeException.java
- src/main/java/org/wso2/callhome/exception/UtilException.java
- src/main/java/org/wso2/callhome/utils/CallHomeInfo.java
- src/main/java/org/wso2/callhome/utils/MessageFormatter.java
- src/main/java/org/wso2/callhome/utils/Util.java
> Adding CallHome core source code to the master branch.
> Split the CallHome core and the Carbon components into separate jars.
> List all JDK versions - Oralce JDK 1.8
> Operating systems - Ubuntu 18.04
> Add CallHome core source code

- pom.xml
> Update pom.xml version

- pom.xml
- src/main/java/org/wso2/callhome/model/UpdateConfig.java
- src/main/java/org/wso2/callhome/utils/Util.java
> Use update configuration values for the Updates 2.0 model
> Use update configuration values for the Updates 2.0 model

- pom.xml
- src/main/java/org/wso2/carbon/callhome/internal/CallHomeComponent.java
- src/main/java/org/wso2/carbon/callhome/internal/CallHomeObserver.java
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> fix callhome ssl issue

- pom.xml
- src/main/java/org/wso2/carbon/callhome/internal/CallHomeComponent.java
- src/main/java/org/wso2/carbon/callhome/internal/CallHomeObserver.java
> Resolves #44 
> Fix SSL issue when enabling Java security manager
> Fix SSL issue when creating a HTTP client

- pom.xml
> Update call-home core version
> Support the update-tool in updates 2.0 model.
> Update call-home core version

- src/main/java/org/wso2/callhome/core/CallHome.java
- src/main/java/org/wso2/callhome/utils/CallHomeInfo.java
- src/main/java/org/wso2/callhome/utils/Util.java
> Resolves #49 
> Fix SSL issue when enabling Java security manager
> Request callhome API endpoint for updates 2.0

- pom.xml
> Update core version in pom.xml
> Update core version in pom.xml

- pom.xml
> Update core version in pom.xml
> Change core version in pom.xml

- pom.xml
> Update call home core version

- pom.xml
> Revert "Update call home core version"

- pom.xml
> Upgrade org.yaml.snakeyaml

- pom.xml
$Subject
Related PR: https://github.com/wso2/call-home/pull/66
> Upgrade core with org.yaml.snakeyaml upgrade

- pom.xml
> Update call home core version to 1.14
> Update Callhome core version to 1.14

- pom.xml
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> Updated the calllhome version to support gson_2.8.9

- pom.xml
> Upgrade the SnakeYAML version to 1.33
> Upgrade SnakeYAML version to 1.33

- pom.xml
$Subject
> Related PRs: https://github.com/wso2/call-home/pull/74
> Upgrade callhome core with org.yaml.snakeyaml upgrade

- pom.xml
To resolve the following build error 
```
Invalid class file META-INF/versions/9/module-info.class (java.lang.ArrayIndexOutOfBoundsException: 19)
```
> Upgrade maven bundle plugin version

- pom.xml
- Change the snake yml dependency
- Use the orbit sanke yml with snake yml 2.0 instead of directly using third party snake yml.
> Change snakeyaml dependency

- pom.xml
> Release build got stuck on the jar uploading step due to uploading through http.
> Add the repository location with https url to fix that.
> Add repository location to call home core
